b07/urls.py
from django.contrib import admin
from django.urls import include, path
from allauth.account.views import LogoutView

from housing import views

from django.conf.urls.static import static
from b07 import settings

urlpatterns = [
    path('', views.index, name='index'),
    path('housing/', include('housing.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('logout', LogoutView.as_view()),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

housing/urls.py
from django.urls import path

from . import views
from allauth.account.views import LogoutView

app_name = 'housing'

urlpatterns = [
    path('', views.index, name='index'),
    path('logout', LogoutView.as_view(), name='logout'),
    path('list/', views.HousingListView.as_view(), name='studentHousingList'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:housing_id>/review_submit/', views.review_submit, name='review_submit'),
    path('manage_reviews/', views.user_review_list, name='review_list'),
    path('submission/', views.SuggestionView.as_view(), name='submission'),
    path('submission/success/', views.successful_submission_view, name='success'),
    path('profile/', views.profile_view, name='profile'),
    path('profile/edit/', views.edit_profile_view, name='edit_profile'),
    path('profile/submit/', views.submit_profile_view, name='submit_profile'),
    path('manage_reviews/delete/<int:review_id>/<int:housing_id>', views.review_delete, name='review_delete'),
    path('manage_reviews/edit/<int:review_id>/', views.review_edit, name='review_edit'),
    path('manage_reviews/edit/<int:review_id>/submit/<int:housing_id>', views.review_edit_submit, name='review_edit_submit'),
]

housing/models.py
from django.db import models
import geocoder

# Create your models here.
class StudentHousing(models.Model):
    name = models.CharField(max_length=200)
    distToGrounds = models.FloatField(default=0)
    parking = models.BooleanField()
    minCost = models.IntegerField(default=0)
    maxCost = models.IntegerField(default=0)
    location = models.TextField(max_length=200, null=True)
    landlordEmail = models.CharField(max_length=200, null=True)
    landlordPhone = models.CharField(max_length=200, null=True)
    amenities = models.TextField(max_length=200, null=True)
    deadline = models.CharField(max_length=200, null=True)
    averageRating = models.FloatField(default=0)
    address = models.TextField(max_length=200, null=True)
    image = models.ImageField(blank=True, null=True) #makes it optional to include an image
    lat = models.FloatField(blank=True, null=True) #leave blank
    long = models.FloatField(blank=True, null=True) #leave blank

    def save(self, *args, **kwargs):
        g = geocoder.mapbox(self.address, key='pk.eyJ1IjoiYXZhbmVlbnAiLCJhIjoiY2t2bnprNGxhMWs1MTJubzB5M2J0OG95eiJ9.xN5gncTvjcamL4-60POirQ')
        g = g.latlng #[lat, long]
        self.lat = g[0]
        self.long = g[1]
        return super(StudentHousing, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

    def valid_parameters(self):
        if self.distToGrounds > 0 and self.minCost > 0 and self.maxCost > 0 and self.averageRating >= 0 and self.averageRating <= 5:
            return True
        else:
            return False


class Review(models.Model):
    house = models.ForeignKey(StudentHousing, on_delete=models.CASCADE)
    rating = models.IntegerField(default=0)
    comment = models.TextField(max_length=200, default="")
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return str(self.pub_date)+' '+str(self.rating)+' '+self.comment[:10]

    def valid_parameters(self):
        if 5 >= self.rating >= 0:
            return True
        else:
            return False


class UserProfile(models.Model):
    email = models.CharField(max_length=320, primary_key=True) # According to Google, the longest email address could have 320 characters
    gender = models.CharField(max_length=20, default="")
    userName = models.CharField(max_length=100, default="")
    age = models.IntegerField(default=0)
    schoolYear = models.CharField(max_length=50, default="")
    major = models.CharField(max_length=50, default="")

    def __str__(self):
        return self.email


class UserReview(models.Model):
    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    review_id = models.IntegerField(default=0)

    def __str__(self):
        return str(self.review_id)


# class UserFavorite(models.Model):
#     user = models.ForeignKey(User, on_delete=models.CASCADE)
#     favorite_housing_id = models.IntegerField(default=0)
#
#     def __str__(self):
#         return str(self.favorite_housing_id)


class SuggestedListings(models.Model):
    Name = models.CharField(max_length=200)
    Address = models.CharField(max_length=500)

    def __str__(self):
        return self.Name

    def valid_parameters(self):
        if len(self.Name) > 0 and len(self.Address) > 0:
            return True
        else:
            return False

housing/forms.py
#created this document using https://docs.djangoproject.com/en/3.2/topics/forms/

from django import forms
from models import Storage

class SuggestedListingName(forms.Form):
    name = forms.CharField(label='Name of housing option:', max_length=200)

class SuggestedListingAddress(forms.Form):
    address = forms.CharField(label='Address:', max_length=500)

class UploadImage(forms.Form):
    image = forms.FileField()

housing/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.views import generic
from django.shortcuts import get_object_or_404
from .models import StudentHousing, Review, UserReview, UserProfile, SuggestedListings
from django.urls import reverse
from django.utils import timezone
from django.db.models import Avg


# Create your views here.
def index(request):
    context = {'studentHousingList': StudentHousing.objects.filter(distToGrounds__gt=0).filter(minCost__gt=0).filter(maxCost__gt=0)\
            .filter(averageRating__gte=0).filter(averageRating__lte=5)}
    if request.user.is_authenticated:
        try:
            u = UserProfile.objects.get(email=request.user.email)
            u.userName = request.user.username
            u.save()
        except UserProfile.DoesNotExist:
            UserProfile.objects.create(email=request.user.email, userName=request.user.username)
    return render(request, 'housing/index.html', context)


class HousingListView(generic.ListView):
    template_name = 'housing/studentHousingList.html'
    context_object_name = 'studentHousing_list'

    def get_queryset(self):
        """
        Return all housing listings.
        """
        return StudentHousing.objects.filter(distToGrounds__gt=0).filter(minCost__gt=0).filter(maxCost__gt=0)\
            .filter(averageRating__gte=0).filter(averageRating__lte=5)


class DetailView(generic.DetailView):
    model = StudentHousing
    template_name = 'housing/studentHousingOption.html'

    def get_queryset(self):
        """
        Return all housing listings.
        """
        return StudentHousing.objects


def review_submit(request, housing_id):
    housing = get_object_or_404(StudentHousing, pk=housing_id)
    try:
        selected_choice = int(request.POST['rating'])
        if selected_choice is None:
            raise ValueError()
    except (KeyError, ValueError):
        return render(request, 'housing/studentHousingOption.html', {
            'studenthousing': housing,
            'error_message': "You didn't select a rating.",
        })
    else:
        r = housing.review_set.create(rating=selected_choice, comment=request.POST['comment'], pub_date=timezone.now())
        housing.averageRating = round(housing.review_set.aggregate(Avg('rating'))['rating__avg'], 1)
        housing.save()
        UserProfile.objects.get(email=request.user.email).userreview_set.create(review_id=r.id)
        return HttpResponseRedirect(reverse('housing:detail', args=(housing_id,)))


def user_review_list(request):
    review_list = Review.objects.filter(id__in=UserProfile.objects.get(email=request.user.email).userreview_set.values_list('review_id', flat=True))
    context = {'review_list': review_list}
    return render(request, 'housing/userReviewList.html', context)


class SuggestionView(generic.CreateView):
    model = SuggestedListings
    template_name = "housing/submission.html"
    fields = ['Name', 'Address']
    success_url = 'success/'


def successful_submission_view(request):
    return render(request, 'housing/successfulSubmission.html')


def profile_view(request):
    context = {'currentuser': UserProfile.objects.get(email=request.user.email)}
    return render(request, 'housing/profile.html', context)


def edit_profile_view(request):
    context = {'currentuser': UserProfile.objects.get(email=request.user.email)}
    return render(request, 'housing/profileEdit.html', context)


def submit_profile_view(request):
    u = get_object_or_404(UserProfile, email=request.user.email)
    # school_year_choices = {'FR': "Freshman", 'SO': "Sophomore", 'JR': "Junior", 'SR': "Senior", 'GR': "Graduate", 'OT': "Other"}
    try:
        gender = (request.POST['gender'])
        age = int(request.POST['age'])
        school_year = request.POST['schoolYear']
        major = (request.POST['major'])
    except KeyError:
        return render(request, 'housing/profileEdit.html', {
            'currentuser': u,
            'error_message': "System error",
        })
    else:
        u.gender = gender
        u.age = age
        u.schoolYear = school_year
        u.major = major
        u.save()
        return HttpResponseRedirect(reverse('housing:profile'))


def review_delete(request, review_id, housing_id):
    get_object_or_404(UserProfile.objects.get(email=request.user.email).userreview_set, review_id=review_id) # Check if the current review belongs to the current user
    r = get_object_or_404(Review, pk=review_id)
    r.delete()
    housing = get_object_or_404(StudentHousing, pk=housing_id)
    try:
        housing.averageRating = round(housing.review_set.aggregate(Avg('rating'))['rating__avg'], 1)
    except:
        housing.averageRating = 0
    housing.save()
    return redirect('housing:review_list')


def review_edit(request, review_id):
    get_object_or_404(UserProfile.objects.get(email=request.user.email).userreview_set, review_id=review_id) # Check if the current review belongs to the current user
    context = {'review': get_object_or_404(Review, pk=review_id)}
    return render(request, 'housing/reviewEdit.html', context)


def review_edit_submit(request, review_id, housing_id):
    get_object_or_404(UserProfile.objects.get(email=request.user.email).userreview_set, review_id=review_id) # Check if the current review belongs to the current user
    r = get_object_or_404(Review, pk=review_id)
    housing = get_object_or_404(StudentHousing, pk=housing_id)
    try:
        rating = (request.POST['rating'])
        comment = (request.POST['comment'])
    except KeyError:
        return render(request, 'housing/reviewEdit.html', {
            'review': get_object_or_404(Review, pk=review_id),
            'error_message': "System error",
        })
    else:
        r.rating = rating
        r.comment = comment
        r.pub_date = timezone.now()
        r.save()
        housing.averageRating = round(housing.review_set.aggregate(Avg('rating'))['rating__avg'], 1)
        housing.save()
        return HttpResponseRedirect(reverse('housing:review_list'))

housing/templates/housing/profile.html
<!doctype html>

<!-- Bootstrap -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<script src='https://api.mapbox.com/mapbox-gl-js/v2.3.1/mapbox-gl.js'></script>
<link href='https://api.mapbox.com/mapbox-gl-js/v2.3.1/mapbox-gl.css' rel='stylesheet' />

{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% load socialaccount %}

<!--<div style="width: 100%" class="shadow p-2 mb-3 bg-body rounded text-white">-->
<!--    <h3 class="font-monospace text-center">Housing for UVA Students by B-07!</h3>-->
<!--</div>-->

<nav class="navbar navbar-expand-lg navbar-dark bg-dark border-bottom box-shadow mb-3">
    <div class="container-fluid">
        <a class="navbar-brand">Housing Website for UVA Students</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
        <span class="navbar-toggler-icon"></span>
      </button>
        <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'index' %}">Homepage</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'housing:studentHousingList' %}">Browse Listings</a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" id="dropdownMenuLink" aria-haspopup="true" aria-expanded="false">Account</a>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                        <a class="dropdown-item nav-link" style="color:black;" href="{% url 'housing:profile' %}">Profile</a>
                        <a class="dropdown-item nav-link" style="color:black;" href="{% url 'housing:review_list' %}">Manage comments</a>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'housing:submission' %}">Suggest a Listing</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'housing:logout' %}">Logout</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% provider_login_url 'google' %}">Login</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

<div class="container">
    <div class="col d-flex justify-content-center">
        <div class="jumbotron">
            <h1 class="display-4">Housing for UVA Students by B-07!</h1>
            <hr class="my-4">
        </div>
    </div>
</div>

<h1 class="display-3 col-md-4 offset-md-4">Profile</h1><br>

{% if currentuser %}
    <ul class="list-group col-md-3 offset-md-4">
        <label class="form-label">User Name</label>
        <li class="list-group-item">{{ currentuser.userName }}</li><br>
        <label class="form-label">Email</label>
        <li class="list-group-item">{{ currentuser.email }}</li><br>
        <label class="form-label">Gender</label>
        <li class="list-group-item">{{ currentuser.gender }}</li><br>
        <label class="form-label">Age</label>
        {% if currentuser.age != 0 %}
            <li class="list-group-item">{{ currentuser.age }}</li><br>
        {% else %}
            <li class="list-group-item"></li><br>
        {% endif %}
        <label class="form-label">School Year</label>
        <li class="list-group-item">{{ currentuser.schoolYear }}</li><br>
        <label class="form-label">Major</label>
        <li class="list-group-item">{{ currentuser.major }}</li><br>
    </ul>
    <a style="text-decoration:none" class="btn btn-primary col-md-1 offset-md-5" href="{% url 'housing:edit_profile' %}">Edit</a><br>
{% else %}
    <p>No profile available.</p>
{% endif %}
<br>

<div style="bottom:0; width:100%" class="card text-center">
    <div class="card-body">
        <h5 class="card-title">Project B-07</h5>
        <p class="card-text">CS3240 Off-Grounds Housing</p>
    </div>
    <div class="card-footer text-muted">
        c. 2021
    </div>
</div>

housing/templates/housing/profileEdit.html
<!doctype html>

<!-- Bootstrap -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<script src='https://api.mapbox.com/mapbox-gl-js/v2.3.1/mapbox-gl.js'></script>
<link href='https://api.mapbox.com/mapbox-gl-js/v2.3.1/mapbox-gl.css' rel='stylesheet' />

{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% load socialaccount %}


{% if error_message %}<p class="col-md-4 offset-md-4"><strong>{{ error_message }}</strong></p>{% endif %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark border-bottom box-shadow mb-3">
    <div class="container-fluid">
        <a class="navbar-brand">Housing Website for UVA Students</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
        <span class="navbar-toggler-icon"></span>
      </button>
        <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'index' %}">Homepage</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'housing:studentHousingList' %}">Browse Listings</a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" id="dropdownMenuLink" aria-haspopup="true" aria-expanded="false">Account</a>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                        <a class="dropdown-item nav-link" style="color:black;" href="{% url 'housing:profile' %}">Profile</a>
                        <a class="dropdown-item nav-link" style="color:black;" href="{% url 'housing:review_list' %}">Manage comments</a>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'housing:submission' %}">Suggest a Listing</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'housing:logout' %}">Logout</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% provider_login_url 'google' %}">Login</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

<div class="container">
    <div class="col d-flex justify-content-center">
        <div class="jumbotron">
            <h1 class="display-4">Housing for UVA Students by B-07!</h1>
            <hr class="my-4">
        </div>
    </div>
</div>

<h1 class="display-3 col-md-4 offset-md-4">Profile Edit</h1><br>

{% if currentuser %}
<ul class="list-group col-md-3 offset-md-4">
    <label class="form-label">User Name</label>
    <li class="list-group-item">{{ currentuser.userName }}</li><br>
    <label class="form-label">Email</label>
    <li class="list-group-item">{{ currentuser.email }}</li><br>
</ul>
<form action="{% url 'housing:submit_profile' %}" method="post">
    {% csrf_token %}
    <div class="col-md-3 offset-md-4">
        <label for="Textarea1" class="form-label">Gender</label>
        <input class="form-control w-100" id="Textarea1" name="gender" value={{currentuser.gender}}></input>
        <br>
    </div>
    <div class="col-md-3 offset-md-4">
        <label for="Textarea2" class="form-label">Age</label>
        <input class="form-control" id="Textarea2" name="age" value={{currentuser.age}}></input>
        <br>
    </div>
    <div class="col-md-3 offset-md-4">
        <label for="Textarea3" class="form-label">School Year</label>
        <select class="form-select" aria-label="Default select example" id="Textarea3" name="schoolYear" value={{currentuser.schoolYear}}>
            <option selected>{{currentuser.schoolYear}}</option>
            <option value="Freshman">Freshman</option>
            <option value="Sophomore">Sophomore</option>
            <option value="Junior">Junior</option>
            <option value="Senior">Senior</option>
            <option value="Graduate">Graduate</option>
            <option value="Other">Other</option>
        </select>
        <br>
    </div>
    <div class="col-md-3 offset-md-4">
        <label for="Textarea4" class="form-label">Major</label>
        <input class="form-control w-100" id="Textarea4" name="major" value={{currentuser.major}}></input>
        <br>
    </div>
    <button class="btn btn-primary col-md-1 offset-md-5" type="submit">Submit</button>
</form>
{% else %}
    <p>No profile available.</p>
{% endif %}
<br>

<div style="bottom:0; width:100%" class="card text-center">
    <div class="card-body">
        <h5 class="card-title">Project B-07</h5>
        <p class="card-text">CS3240 Off-Grounds Housing</p>
    </div>
    <div class="card-footer text-muted">
        c. 2021
    </div>
</div>

housing/templates/housing/submission.html
<!doctype html>

<!-- Bootstrap -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<script src='https://api.mapbox.com/mapbox-gl-js/v2.3.1/mapbox-gl.js'></script>
<link href='https://api.mapbox.com/mapbox-gl-js/v2.3.1/mapbox-gl.css' rel='stylesheet' /> {% load bootstrap5 %} {% bootstrap_css %} {% bootstrap_javascript %} {% load socialaccount %}


<nav class="navbar navbar-expand-lg navbar-dark bg-dark border-bottom box-shadow mb-3">
    <div class="container-fluid">
        <a class="navbar-brand">Housing Website for UVA Students</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
        <span class="navbar-toggler-icon"></span>
      </button>
        <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'index' %}">Homepage</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'housing:studentHousingList' %}">Browse Listings</a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" id="dropdownMenuLink" aria-haspopup="true" aria-expanded="false">Account</a>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                        <a class="dropdown-item nav-link" style="color:black;" href="{% url 'housing:profile' %}">Profile</a>
                        <a class="dropdown-item nav-link" style="color:black;" href="{% url 'housing:review_list' %}">Manage comments</a>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'housing:submission' %}">Suggest a Listing</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'housing:logout' %}">Logout</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% provider_login_url 'google' %}">Login</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

<div class="container">
    <div class="col d-flex justify-content-center">
        <div class="jumbotron">
            <h1 class="display-4">Housing for UVA Students by B-07!</h1>
            <hr class="my-4">
        </div>
    </div>
</div>

{% if user.is_authenticated %}
<div style="font-size:120%">
    <p class="font-weight-bold display-6" style="margin-left: 10px">Hi, {{ user.username }}! Want to suggest a listing to add?</p>
</div>

<div class="container">
    <div class="row">
        <div class="col-md-12 d-flex flex-column justify-content-center">
            <div class="row">
                <div class="col-lg-6 col-md-8 mx-auto">
                    <div class="card rounded shadow shadow-sm">
                        <div class="card-header">
                            <h3 class="mb-0">Submit your suggestion here:</h3>
                        </div>
                        <div class="card-body d-flex justify-content-center">
                            <form method="post">{% csrf_token %} {{form.as_p}}
                                <input type="submit" class="btn btn-primary" value="Submit suggested listing">
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<br><br>



{% endif %}

<div style="bottom:0; width:100%" class="card text-center">
    <div class="card-body">
        <h5 class="card-title">Project B-07</h5>
        <p class="card-text">CS3240 Off-Grounds Housing</p>
    </div>
    <div class="card-footer text-muted">
        c. 2021
    </div>
</div>

housing/templates/housing/userReviewList.html
<!doctype html>

<!-- Bootstrap -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">

{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% load socialaccount %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark border-bottom box-shadow mb-3">
    <div class="container-fluid">
        <a class="navbar-brand">Housing Website for UVA Students</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
        <span class="navbar-toggler-icon"></span>
      </button>
        <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'index' %}">Homepage</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'housing:studentHousingList' %}">Browse Listings</a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" id="dropdownMenuLink" aria-haspopup="true" aria-expanded="false">Account</a>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                        <a class="dropdown-item nav-link" style="color:black;" href="{% url 'housing:profile' %}">Profile</a>
                        <a class="dropdown-item nav-link" style="color:black;" href="{% url 'housing:review_list' %}">Manage comments</a>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'housing:submission' %}">Suggest a Listing</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'housing:logout' %}">Logout</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% provider_login_url 'google' %}">Login</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

<div class="container">
    <div class="col d-flex justify-content-center">
        <div class="jumbotron">
            <h1 class="display-4">Housing for UVA Students by B-07!</h1>
            <hr class="my-4">
        </div>
    </div>
</div>

{% if user.is_authenticated %}
<div style="font-size:120%">
    <p class="font-weight-bold display-6" style="margin-left: 10px">Hi, {{ user.username }}! Here are your reviews:</p>
</div>
{% endif %}

{% if review_list %}
    <ol class="list-group col-md-8 offset-md-2">
    {% for review in review_list %}
        <li class="list-group-item d-flex justify-content-between align-items-start">
            <div class="ms-2 me-auto">
                <div class="fw-bold"><a style="text-decoration:none; color:black;" href="{% url 'housing:detail' review.house.id %}">{{ review.house }}</a></div>
                Rating: {{ review.rating }}<br>
                Comment: {{ review.comment }}<br>
                Time: {{ review.pub_date }}
            </div>
            <small><a class="btn btn-primary" href="{% url 'housing:review_edit' review.id %}">Edit</a> <a class="btn btn-danger" href="{% url 'housing:review_delete' review.id review.house.id%}">Delete</a></small>
        </li>
<!--        <dt class="text-uppercase fw-bolder"><a style="text-decoration:none" href="{% url 'housing:detail' review.house.id %}"><strong>{{ review.house }}</strong></a></dt>-->
<!--        <dd class="badge bg-white text-danger text-primary fw-light"><em>Rating: {{ review.rating }}</em></dd>-->
<!--        <dd class="badge bg-white text-danger text-primary fw-light"><em>Review: {{ review.comment }}</em></dd>-->
<!--        <dd class="badge bg-white text-danger text-primary fw-light"><em>Posted on: {{ review.pub_date }}</em></dd>-->
        <br>
    {% endfor %}
    </ol>
{% else %}
    <p>No reviews available.</p>
{% endif %}

<div style="bottom:0; width:100%" class="card text-center">
    <div class="card-body">
        <h5 class="card-title">Project B-07</h5>
        <p class="card-text">CS3240 Off-Grounds Housing</p>
    </div>
    <div class="card-footer text-muted">
        c. 2021
    </div>
</div>